# This Conda environment simulates the environment on the
# production machines.
# Usage:
# conda env create -f environment.yml

name: uflo
channels:
  - defaults
dependencies:
  - python=3.5
  - requests=2.24
  - pip=9
  - pip:
    - arrow==0.14.6
