# This Conda environment simulates the environment on the
# production machines.
# Usage:
# conda env create -f environment.yml

name: uflo
channels:
  - defaults
dependencies:
  - python=3.6
  - requests=2.27
  - pip
  - numpy=1.21
  - pip:
    - arrow~=0.17
